name: my first workflow

on: push

jobs:
  My_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello there"

      - name: list files
        run: ls

      - name: read readme
        run: cat readme.md
