name: matrix conf

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [alpine, hello-world]
    runs-on: ${{ matrix.os }}
    steps:
      - name: verify docker
        run: docker info
      - name: Run image on  ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
