name: multiple-job

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Runn for cover, I am Dragon" >> dragon.txt

      - name: generate cool banner into android.txt
        run: sleep 10

      - name: Upload dragon.txt
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dragon.txt

      - name: Sleep for 30 sec
        run: sleep 10

      - name: test file exists
        run: grep -i "dragon" dragon.txt

      - name: Sleep for 30 seconds
        run: sleep 10

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest

    steps:
      - name: read file
        run: cat dragon.txt
