name: multiple-job

on: push

env:
  IMAGE_NAME: mywebapp
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t ${{ secrets.DOCKER_REGISTRY }}.$DOCKER_USERNAME.$IMAGE_NAME:latest

      - name: Docker login
        run: echo docker login -username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: echo docker push ${{ secrets.DOCKER_REGISTRY }}.$DOCKER_USERNAME.$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY APPLICATION
        run: echo deploying ${{ env.IMAGE_NAME }} |
          sleep 10 |
          echo deployed !
